const generateColdEmail = async (req, res) => {
  try {
    const {
      recruiterName,
      company,
      role,
      userName,
      portfolio,
      reason,
      skills,
      experience,
      tone,
    } = req.body;

    if (!company || !role || !userName) {
      return res.status(400).json({
        message: "Company, role, and your name are required",
      });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.status(500).json({
        message: "Gemini API key is missing in backend .env",
      });
    }

    const { GoogleGenAI } = await import("@google/genai");

    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const toneInstructions = {
  Professional: {
    style: "Polished, formal, and recruiter-friendly. Clear sentence structure. No contractions. Respectful distance.",
    wordLimit: "150–180 words",
    greeting: recruiterName ? `Dear ${recruiterName},` : "Dear Hiring Team,",
  },
  Friendly: {
    style: "Warm, conversational, and human. Light contractions allowed (I'm, I've, you're). Sounds like a real person, not a template.",
    wordLimit: "130–160 words",
    greeting: recruiterName ? `Hi ${recruiterName},` : "Hi there,",
  },
  Confident: {
    style: "Direct and self-assured. Lead with value. No hedging phrases like 'I think' or 'I feel'. Bold but not arrogant.",
    wordLimit: "140–170 words",
    greeting: recruiterName ? `Hi ${recruiterName},` : "Hi,",
  },
  "Short and Direct": {
    style: "Ultra-concise. Every sentence earns its place. No filler, no pleasantries beyond one line. Ruthlessly focused.",
    wordLimit: "Under 90 words",
    greeting: recruiterName ? `Hi ${recruiterName},` : "Hi,",
  },
};

const selected = toneInstructions[tone] || toneInstructions["Professional"];

const safePortfolio =
  portfolio && portfolio.trim()
    ? portfolio
    : "[Portfolio/GitHub/LinkedIn — add before sending]";

const hasSkills = skills && skills.trim();
const hasExperience = experience && experience.trim();
const hasReason = reason && reason.trim();
const isExperienced = hasExperience && experience.trim().split(" ").length > 10;

const prompt = `
You are a world-class career coach who writes cold emails that actually get replies. Your emails sound like they were written by a real, thoughtful human — not generated by AI.

═══════════════════════════════
CANDIDATE BRIEF
═══════════════════════════════
Name: ${userName}
Applying for: ${role} at ${company}
${recruiterName ? `Recruiter: ${recruiterName}` : "Recruiter name: Unknown"}
${hasSkills ? `Core skills: ${skills}` : ""}
${hasExperience ? `Background: ${experience}` : "Fresher/Student with no listed experience"}
${hasReason ? `Why this company/role: ${reason}` : ""}
Portfolio/Links: ${safePortfolio}
Candidate level: ${isExperienced ? "Has relevant experience/projects" : "Student or entry-level"}

═══════════════════════════════
TONE & STYLE
═══════════════════════════════
Tone: ${tone}
Style guide: ${selected.style}
Word count: ${selected.wordLimit}
Opening greeting: ${selected.greeting}

═══════════════════════════════
STRICT WRITING RULES
═══════════════════════════════

STRUCTURE (follow this exactly):
1. Subject line — specific, compelling, not generic. Reference the role and one hook (skill, project, or insight).
2. Opening — one sentence. State who you are and why you are writing. No flattery.
3. Body — two to three sentences max. Mention only skills/projects the candidate provided. Connect them directly to what ${company} likely needs for a ${role}. If no experience provided, focus on skills and genuine interest.
4. Link — naturally weave in the portfolio/GitHub link as proof of work.
5. CTA — one clear ask. "Would you be open to a quick call?" or "I'd love to share more if there's a fit." Not both.
6. Sign-off — "Best regards," or "Best," then the candidate's name only.

BANNED phrases (never use these):
- "I have long admired"
- "I am passionate about"  
- "I believe I would be a great fit"
- "I came across your company"
- "It has always been my dream"
- "I am excited about the opportunity"
- "Please find attached"
- "I think I have what it takes"
- "To whom it may concern"
- "I look forward to hearing from you" (too overused — find a fresher CTA)
- Any generic AI filler

BANNED behaviors:
- Do not invent projects, internships, metrics, or achievements not provided
- Do not reference specific company products, missions, or values unless the candidate gave a reason
- Do not use "Dear Mr./Ms." without a last name
- Do not write more than one CTA
- Do not add any commentary before or after the email
- Do not use bullet points inside the email body
- Do not mention AI, ChatGPT, or that this email was generated

QUALITY CHECKS before outputting:
✓ Does the opening avoid flattery?
✓ Is every claim backed by what the candidate provided?
✓ Does it sound like a human wrote it at 11pm before a deadline?
✓ Would a recruiter read past line 2?
✓ Is the CTA clear and singular?
✓ Is it within word count?

═══════════════════════════════
OUTPUT FORMAT (exactly this, nothing else)
═══════════════════════════════

Subject: [subject line]

${selected.greeting}

[email body]

Best regards,
${userName}
${safePortfolio !== "[Portfolio/GitHub/LinkedIn — add before sending]" ? safePortfolio : ""}
`;
    const response = await ai.models.generateContent({
     model: "gemini-3.1-flash-lite",
      contents: prompt,
    });

    return res.status(200).json({
      email: response.text,
    });
  } catch (error) {
    console.log("Gemini backend error:", error);

    return res.status(500).json({
      message: "AI email generation failed",
      error: error.message,
    });
  }
};

module.exports = { generateColdEmail };